version: '3.8'

services:
  backend:
    build: radium_backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/radium_db
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: radium_db
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./radium_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data: